### ISSUE TITLE
Ripple Layer frame is not updating on Orientation Change. 

### ISSUE THREAD

**Issue by BalaSportsGravy** [phhai1710/VideoQuickSeeking#2]
On user rotating the phone, Ripple Layer frame is not updating and stick to the initial frame itself. I have tried to update using constraints but the frame is not updating. Any workaround for this?

**Comment by phhai1710** [comment]
Hi @BalaSportsGravy , thank you for your check. I have fixed it in version 1.0.3 by this commit https://github.com/phhai1710/VideoQuickSeeking/commit/b37fb8ebf32acaf66c538bc4ba38c907db2d2c2d

**Comment by BalaSportsGravy** [comment]
Thanks for your update @phhai1710
